=== Nojjia/MDX-CST1340-Coursework/products.dtd
<!--TO-DO:
     - Assign more appropirate element names
-->

<!--ROOT-->
<!ELEMENT products (medicines, medical_devices, others)>

<!--MAIN-CONTAINERS-->
<!ELEMENT medicines (medicine*)>
<!ELEMENT medical_devices (medical_device*)>
<!ELEMENT others (other*)>

<!--SUB-CONTAINERs-->
<!ELEMENT medicine (thumbnail?, name, description?, ingredients?, method_of_administration?, dosage, price, in_stock, manufacturer?, type)>
<!ELEMENT medical_device (thumbnail?, name, description, price, in_stock, manufacturer)>
<!ELEMENT other (thumbnail?, name, description?, ingredients, method_of_administration, dosage, price, in_stock, manufacturer, type)>

<!--ELEMENT-->
<!ELEMENT thumbnail (#PCDATA)>

<!--ELEMENT-->
<!ELEMENT name (#PCDATA)>

<!--ELEMENT-->
<!ELEMENT description (#PCDATA)>

<!--ELEMENT-->
<!ELEMENT ingredients (ingredient+)>
<!ELEMENT ingredient (#PCDATA)>

<!--ELEMENT-->
<!ELEMENT method_of_administration (Oral | Topical | Transdermal | Intravenous | Intramuscular | Subcutaneous | Inhalation | Rectal | Unknown)>
<!--ELEMENT-DATA-->
<!ELEMENT Oral EMPTY>
<!ELEMENT Topical EMPTY>
<!ELEMENT Transdermal EMPTY>
<!ELEMENT Intravenous EMPTY>
<!ELEMENT Intramuscular EMPTY>
<!ELEMENT Subcutaneous EMPTY>
<!ELEMENT Inhalation EMPTY>
<!ELEMENT Rectal EMPTY>
<!ELEMENT Unknown EMPTY>

<!--ELEMENT-->
<!ELEMENT dosage (#PCDATA)>

<!--ELEMENT-->
<!ELEMENT price (#PCDATA)>

<!--ELEMENT-->
<!ELEMENT in_stock (yes | no)>
<!ELEMENT yes EMPTY>
<!ELEMENT no EMPTY>

<!--ELEMENT-->
<!ELEMENT manufacturer (#PCDATA)>

<!--ELEMENT-->
<!ELEMENT type (drugs | dietary_supplements | cosmetics_care)>
<!--ELEMENT-DATA-->
<!ELEMENT drugs EMPTY>
<!ELEMENT dietary_supplements EMPTY>
<!ELEMENT cosmetics_care EMPTY>

=== Nojjia/MDX-CST1340-Coursework/products.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="products.xsl"?>
<!DOCTYPE products SYSTEM "products.dtd">

<!--TO-DO:
	- Fix the horrible layout
	- Add info, or remove, and subsequently edit dtd
-->

<products>
	<medicines>
		<medicine>
			<thumbnail>
				thumbnail_1.png
			</thumbnail>
			<name>
				name 1
			</name>
			<description>
				description 1
			</description>
			<ingredients>
				<ingredient>
					ingredient 1 1
				</ingredient>
				<ingredient>
					ingredient 1 2
				</ingredient>
				<ingredient>
					ingredient 1 3
				</ingredient>
				<ingredient>
					ingredient 1 4
				</ingredient>
			</ingredients>
			<method_of_administration>
				<Oral/>
			</method_of_administration>
			<dosage>
				dosage 1
			</dosage>
			<price>
				price 1
			</price>
			<in_stock
				><no/>
			</in_stock>
			<manufacturer>
				manufacturer 1
			</manufacturer>
			<type>
				<drugs/>
			</type>
		</medicine>
		<medicine>
			<thumbnail>
				thumbnail_1.png
			</thumbnail>
			<name>
				name 1
			</name>
			<description>
				description 1
			</description>
			<ingredients>
				<ingredient>
					ingredient 1 1
				</ingredient>
				<ingredient>
					ingredient 1 2
				</ingredient>
				<ingredient>
					ingredient 1 3
				</ingredient>
				<ingredient>
					ingredient 1 4
				</ingredient>
			</ingredients>
			<method_of_administration>
				<Oral/>
			</method_of_administration>
			<dosage>
				dosage 1
			</dosage>
			<price>
				price 1
			</price>
			<in_stock
				><no/>
			</in_stock>
			<manufacturer>
				manufacturer 1
			</manufacturer>
			<type>
				<drugs/>
			</type>
		</medicine>
		<medicine>
			<thumbnail>
				thumbnail_1.png
			</thumbnail>
			<name>
				name 1
			</name>
			<description>
				description 1
			</description>
			<ingredients>
				<ingredient>
					ingredient 1 1
				</ingredient>
				<ingredient>
					ingredient 1 2
				</ingredient>
				<ingredient>
					ingredient 1 3
				</ingredient>
				<ingredient>
					ingredient 1 4
				</ingredient>
			</ingredients>
			<method_of_administration>
				<Oral/>
			</method_of_administration>
			<dosage>
				dosage 1
			</dosage>
			<price>
				price 1
			</price>
			<in_stock
				><no/>
			</in_stock>
			<manufacturer>
				manufacturer 1
			</manufacturer>
			<type>
				<drugs/>
			</type>
		</medicine>
	</medicines>

	<medical_devices>
		<medical_device>
			<thumbnail>
				thumbnail_1.png
			</thumbnail>
			<name>
				name 1
			</name>
			<description>
				description 1
			</description>
			<price>
				price 1
			</price>
			<in_stock>
				<no/>
			</in_stock>
			<manufacturer>
				manufacturer 1
			</manufacturer>
		</medical_device>
		<medical_device>
			<thumbnail>
				thumbnail_1.png
			</thumbnail>
			<name>
				name 1
			</name>
			<description>
				description 1
			</description>
			<price>
				price 1
			</price>
			<in_stock>
				<no/>
			</in_stock>
			<manufacturer>
				manufacturer 1
			</manufacturer>
		</medical_device>
		<medical_device>
			<thumbnail>
				thumbnail_1.png
			</thumbnail>
			<name>
				name 1
			</name>
			<description>
				description 1
			</description>
			<price>
				price 1
			</price>
			<in_stock>
				<no/>
			</in_stock>
			<manufacturer>
				manufacturer 1
			</manufacturer>
		</medical_device>
	</medical_devices>

	<others>
		<other>
			<thumbnail>
				thumbnail_1.png
			</thumbnail>
			<name>
				name 1
			</name>
			<description>
				description 1
			</description>
			<ingredients>
				<ingredient>
					ingredient 1 1
				</ingredient>
				<ingredient>
					ingredient 1 2
				</ingredient>
				<ingredient>
					ingredient 1 3
				</ingredient>
				<ingredient>
					ingredient 1 4
				</ingredient>
			</ingredients>
			<method_of_administration>
				<Oral/>
			</method_of_administration>
			<dosage>
				dosage 1
			</dosage>
			<price>
				price 1
			</price>
			<in_stock
				><no/>
			</in_stock>
			<manufacturer>
				manufacturer 1
			</manufacturer>
			<type>
				<drugs/>
			</type>
		</other>
		<other>
			<thumbnail>
				thumbnail_1.png
			</thumbnail>
			<name>
				name 1
			</name>
			<description>
				description 1
			</description>
			<ingredients>
				<ingredient>
					ingredient 1 1
				</ingredient>
				<ingredient>
					ingredient 1 2
				</ingredient>
				<ingredient>
					ingredient 1 3
				</ingredient>
				<ingredient>
					ingredient 1 4
				</ingredient>
			</ingredients>
			<method_of_administration>
				<Oral/>
			</method_of_administration>
			<dosage>
				dosage 1
			</dosage>
			<price>
				price 1
			</price>
			<in_stock
				><no/>
			</in_stock>
			<manufacturer>
				manufacturer 1
			</manufacturer>
			<type>
				<drugs/>
			</type>
		</other>
		<other>
			<thumbnail>
				thumbnail_1.png
			</thumbnail>
			<name>
				name 1
			</name>
			<description>
				description 1
			</description>
			<ingredients>
				<ingredient>
					ingredient 1 1
				</ingredient>
				<ingredient>
					ingredient 1 2
				</ingredient>
				<ingredient>
					ingredient 1 3
				</ingredient>
				<ingredient>
					ingredient 1 4
				</ingredient>
			</ingredients>
			<method_of_administration>
				<Oral/>
			</method_of_administration>
			<dosage>
				dosage 1
			</dosage>
			<price>
				price 1
			</price>
			<in_stock
				><no/>
			</in_stock>
			<manufacturer>
				manufacturer 1
			</manufacturer>
			<type>
				<drugs/>
			</type>
		</other>
		<other>
			<thumbnail>
				thumbnail_1.png
			</thumbnail>
			<name>
				name 1
			</name>
			<description>
				description 1
			</description>
			<ingredients>
				<ingredient>
					ingredient 1 1
				</ingredient>
				<ingredient>
					ingredient 1 2
				</ingredient>
				<ingredient>
					ingredient 1 3
				</ingredient>
				<ingredient>
					ingredient 1 4
				</ingredient>
			</ingredients>
			<method_of_administration>
				<Oral/>
			</method_of_administration>
			<dosage>
				dosage 1
			</dosage>
			<price>
				price 1
			</price>
			<in_stock
				><no/>
			</in_stock>
			<manufacturer>
				manufacturer 1
			</manufacturer>
			<type>
				<drugs/>
			</type>
		</other>
	</others>
</products>
